project:
  type: website
  output-dir: docs
  
website:
  title: "Rookie Numbers"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tipoff.qmd
        text: About
      - projects.qmd
    tools:
      - icon: github
        href: https://github.com/carliescheer/rookienumbers
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Carlie Scheer"

format:
  html:
    theme: lux
    toc: true

editor: source

