project:
  type: website
  output-dir: docs
  
website:
  title: "Rookie Numbers"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tipoff.qmd
        text: About
      - href: weeklypredictions.qmd
        text: Weekly Predictions
      - href: weeklyanalysis.qmd
        text: Weekly Analysis
    tools:
      - icon: github
        href: https://github.com/carliescheer/rookienumbers
format:
  html:
    theme: lux
    toc: true

editor: source

