---
title: "Welcome!"
---

What better way to start this than with a disclaimer? I'm just going to put it out there early, because I'm really not in the mood for a lawsuit or for any sort of drama: **Everything I'm doing on here, analyzing, or writing is purely for my own enjoyment, for me to learn, and for me to gain real-world experience in a field that I find fascinating. I am not 21; I cannot legally bet. I'm not betting; I'm simply making predictions based on data and my observations. If I refer to something as a "bet," please know that I am not actually betting - I just don't have the energy to write "simulated bet" out every time. Take everything you see on here with a grain of salt; the reality is I'm probably no better than any person who randomly places bets based on which team mascot they think sounds cooler. Moral of the story - I'm just trying to have fun with this and learn, and hopefully you will as well. Thanks.**

I typed out a longer version of that in the "About" section, so feel free to check that out if you're wondering who the person behind the website is. Anyway, the "About" portion is really just a CYA section. 

Here's an overview of the site before I lose you: 
1. **About**: Get to know me and my goals.
2. **Weekly Predictions**: Check here each week for my predictions for the upcoming week. I'll try to post these each Sunday for the upcoming week (Monday through the following Sunday); as a student, though, I can't make any promises. Basically, I'll be outlining bets I think are smart based on data I've collected or things I've observed. I'll probably stick to 10 or so games each week, but that number may be smaller or larger based on the week and based on how I decide to do things. 
3. **Weekly Analysis**: This will be posted (hopefully) on the Monday after the week I've predicted ends. I'll just be discussing where I went right, and where I went wrong - probably much more of the latter. I'm basically looking at this as a documentation of what I've learned over time. 
4. **Buzzer Beaters**: I'll add fun things to this section that don't apply to any of the other sections. It'll essentially just be the place where I mess around and include things that are either important to the college basketball world or random data I've analyzed. 
5. **Archive**: This will be where I'll add the predictions and analysis from past weeks. 

And as always, remember that UNC sucks (GTHC) and Tom Izzo's teams are always overrated. Thanks for checking this out. 