---
title: "Tip-Off: Get to Know Me!"
---

## Who am I? What am I doing here?

How's it going, college basketball fanatics. A new season is upon us! So, the countdown to March begins...

Ok, you're probably like - who is this kid. Well, I'm currently a student at Duke University with a love for college basketball; I mean, what Duke student isn't (news flash, there's actually a lot of them that couldn't care less). I'm in a program that recently met with the head of analytics for the Boston Celtics - pretty cool, right - and he gave us some great advice, which I'm looking to follow. Future employers, hit me up! 

Anyway, I recently started tracking some sports bets on a spreadsheet for multiple reasons: (1) I find the world of sports to be fascinating, and likewise, the betting industry is booming; (2) I'm not old enough to gamble, I don't have enough money, and although my parents have offered to place bets for me, I'm a major rule follower; (3) I want to gain experience with "simulated" betting before I start placing bets when it's legal for me to do so; and, finally, (4) I'm probably a gambling addict in the making. 
So far, I've been tracking college football and dabbling in NFL games, and it's safe to say I've lost more bets than I've won. I'm having fun doing it, though! As college basketball season approaches - my true love - I've decided to take things more seriously as we prepare for this new season. So here goes nothing. 

## What to expect

This season, I'm hoping to stick with my current method of "placing" weekly bets and immersing myself further into the world of sports and gambling; again, remember that I am not actually using real money for this - it is purely a simulation. I hope that's clear - I mean, I bolded it and everything. I just figured I should put that disclaimer in there so that one day when I get super famous from this, no one can sue me when they lose a bet I advertised on here. 

Each week, I plan on highlighting the games I'm looking forward to, whether I'm "betting" on them or not. I'll probably have a few categories: games I'm placing wagers on, games to be weary of, and games I'd stay away from. Who knows - that's why the site is called "Rookie Numbers." 

After the week is over, I'll go through each category and summarize the results of each game, discuss whether I won the bet or not, and reflect on how I can adjust for future weeks. This is meant to be a learning experience for me, and I'm going to do my best to track my thought process over time to see where I'm making critical errors or where my judgement is correct (which will probably be rare). 


## 19:59 - Let the games begin.

Hopefully you find the idea of this interesting, and if you don't, you probably didn't read all the way to this point anyway. I'm excited to get this started, and I hope you are as well. As always, I'm open to any feedback regarding how I can improve or new segments you want me to include. The only thing I ask is that you keep in mind one thing: I'm doing this for fun and to learn. You're welcome to disagree with my takes, but I'm not ever claiming to be "correct" or "know" anything. I'm just a kid with a dream of working in the sports industry, and this is the best way I can think of getting started. 

Go Blue Devils!