---
title: "Weekly Analysis"
---
## Overview

If you haven't checked out my weekly predictions, go there first. This will be a break-down of those games, where I'll discuss what went well and what went wrong. 

Again, each will be broken down by conference and date. Some summaries may be shorter than others. Note that I do not watch most of the games (sorry), so I won't be providing analysis on the actual game play - just the data I'm seeing, which again isn't much. The only team that you might get some details on is...wait for it...Duke. 

## Weeks 1, 2, and 3

There will be no analysis because I am not making predictions yet. This will begin in Week 4. 

## Week 4: 11/27/2023 - 12/3/2023 

# ACC

1. **Pittsburgh**/Missouri, Pitt -6.5: 
**Final Score**: **Missouri** 71, Pitt 64

Well...I was wrong. Pitt was at the very top of the list for ACC win multipliers and had outperformed in nearly every game this season. If I had SEC data, maybe I wouldn't have made this prediction. 

2. **Duke**/Arkansas, Duke -4.5: 
**Final Score**: **Arkansas** 80, Duke 75

Turns out Duke really is just not that great. Hurts my heart. I really thought 4.5 would be easy to cover with Arkansas' best player being out following that injury during the UNC game, but Arkansas played well in a great atmosphere and Duke essentially did the opposite. 

3. Virginia/**Texas A&M**, Texas A&M +1.5: 
**Final Score**: **Virginia** 59, Texas A&M 47

And that makes me 0/3 in the ACC! Part of this came from the fact that Mike Elko left Duke for Texas A&M this week...in the middle of the night...without telling his players in person...after saying he loved Durham. So yeah, it might've been a bit of an emotional bet in the first place, but I actually PICKED A&M. They were ranked and Virginia had some pretty rough losses earlier in the season. I will say, the over/under for Virginia is probably fairly solid on the under side.  

# Big 12

1. **Oklahoma**/Arkansas Pine-Bluff, Oklahoma -27.5: 
**Final Score**: **Oklahoma** 107, Arkansas Pine-Bluff 86

I'm not that mad about this one because, again, Oklahoma was consistently outperforming, and it's clear that scoring 107 points indicates they have a team of shooters. I'm a little surprised that Pine-Bluff got 86, but I still am a fan of this Oklahoma team and the spread. 

2. **BYU**/Fresno State, BYU -14.5: 
**Final Score**: **BYU** 85, Fresno State 56

My first correct prediction! Embarrassing. Anyway, one thing that isn't embarrassing is this BYU team. Their win multiplier is nearly 2.0 which means they are almost doubling the spread every time. Actually, here they exactly doubled it! Right now there is absolutely no reason to bet against them; this is a really solid team. 

# Big 10

1. **Purdue**/Texas Southern, Purdue -31.5: 
**Final Score**: **Purdue** 99, Texas Southern 67

PHEW this was a close one. Depending on which site you use this could've definitely been a missed bet, but FanDuel's spread pulled it out by a mere .5 points. If I've learned one thing, it's that I need to limit the games I consider once the spread gets higher than ~20 or 25 points. 

2. **Purdue**/Northwestern, Purdue -8.5: 
**Final Score**: Purdue 88, **Northwestern** 92

I actually thought I had convincing evidence on this one, especially given that they're from the same conference. Ugh. You live and you learn. Interesting note: Every time I picked Northwestern during football season, I "won" the bet. So maybe they're just consistently underrated. 

